#!/bin/bash
#
#SBATCH --job-name=single_mol
#SBATCH -e slurm-%j.err                # Separate error file
#SBATCH -o slurm-%j.out                # Output file
#SBATCH --ntasks-per-node=1            ## Number of tasks per node
#SBATCH --cpus-per-task=1              ## Number of CPUs per task
#SBATCH --nodes=1                      ## Number of nodes to be used
#SBATCH -p short.36
#SBATCH --time=24:00:00


# Echo start time and set OMP_NUM_THREADS
echo "# Starting calculation: $(date)"
export OMP_NUM_THREADS=${SLURM_NTASKS_PER_NODE}
echo "OMP_NUM_THREADS=${OMP_NUM_THREADS}"

# Define variables inside the script
gro_file="PABA_480_NPT-Produc_CRpcoupl_300K-initial-geo-100ps.gro"
output_file="1PBA.pdb"

"python" single_molecule.py --gro_file "${gro_file}" --output_file "${output_file}"
# Echo end time
echo "# Ending calculation: $(date)"
